### ISSUE TITLE
Various actions generate errors

### ISSUE THREAD

**Issue by Adarain** [Arthur-Milchior/anki-trigger-action-on-note#15]
With the most recent update, several actions cause pop-up errors.

> Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-18 14:24:58

Upon selecting an entry in the cards browser:

> Caught exception:
Traceback (most recent call last):
  File "aqt\browser.py", line 787, in onRowChanged
  File "aqt\editor.py", line 533, in saveNow
  File "aqt\editor.py", line 652, in saveTags
  File "C:\Users\sasch\AppData\Roaming\Anki2\addons21\1981494159\onFlush.py", line 35, in flushNote
    oldFlushNote(self, mod=mod)
TypeError: flush() got an unexpected keyword argument 'mod'

Upon closing the browser:

> Caught exception:
Traceback (most recent call last):
  File "aqt\browser.py", line 564, in closeEvent
  File "aqt\editor.py", line 533, in saveNow
  File "aqt\editor.py", line 652, in saveTags
  File "C:\Users\sasch\AppData\Roaming\Anki2\addons21\1981494159\onFlush.py", line 35, in flushNote
    oldFlushNote(self, mod=mod)
TypeError: flush() got an unexpected keyword argument 'mod'

Upon attempting to close Anki itself (prevents anki from closing)

> Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1018, in closeEvent
  File "aqt\main.py", line 451, in unloadProfileAndExit
  File "aqt\main.py", line 428, in unloadProfile
  File "aqt\main.py", line 537, in unloadCollection
  File "aqt\main.py", line 808, in closeAllWindows
  File "aqt\__init__.py", line 133, in closeAll
  File "aqt\browser.py", line 586, in closeWithCallback
  File "aqt\editor.py", line 533, in saveNow
  File "aqt\editor.py", line 652, in saveTags
  File "C:\Users\sasch\AppData\Roaming\Anki2\addons21\1981494159\onFlush.py", line 35, in flushNote
    oldFlushNote(self, mod=mod)
TypeError: flush() got an unexpected keyword argument 'mod'

The error does not appear when pressing the button to apply trigger→action rules, which seems to work fine (in particular, the any/all issue appears to indeed have been resolved).

**Comment by Arthur-Milchior** [comment]
Thanks. Corrected normalyl. can you check and confirm please?

**Comment by Adarain** [comment]
Bug appears fixed, I’ve toyed around a bit and haven’t run across any problems.
