### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5' for Anki 23.12.1

### ISSUE THREAD

**Issue by jzohrab** [Arthur-Milchior/anki-trigger-action-on-note#22]
Hello, thanks for the add-on!  It stopped working after a recent upgrade.  I was wondering if you were aware, and/or were planning to work on a fix for this.

If not, let me know, perhaps I can look into it and open a PR back to this repo.  I may need some guidance.  Cheers!

```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.4.1-arm64-arm-64bit

When loading Trigger and actions change one card depending on what occurs on another card:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/jeff/Library/Application Support/Anki2/addons21/1981494159/__init__.py", line 1, in <module>
    from . import browser, main, onFlush
  File "/Users/jeff/Library/Application Support/Anki2/addons21/1981494159/browser.py", line 1, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by jzohrab** [comment]
Opened a draft PR to start the discussion, hopefully that helps us work it out.  Let me know what next steps I may take to help you out.  Cheers!

**Comment by jzohrab** [comment]
Hi @Arthur-Milchior - can I help resolve this problem?  It's failing on 

Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
